import AppKit
import Foundation

/// One captured pasteboard entry. History is memory-only by design: nothing is
/// ever written to disk, and quitting MacForge clears it.
struct ClipboardHistoryItem: Identifiable, Hashable {
    enum Kind: Hashable {
        case text
        case fileURLs([String])
    }

    let id: UUID
    var kind: Kind
    var text: String
    var capturedAt: Date

    init(id: UUID = UUID(), kind: Kind = .text, text: String, capturedAt: Date) {
        self.id = id
        self.kind = kind
        self.text = text
        self.capturedAt = capturedAt
    }

    /// Single-line preview for the list row.
    var preview: String {
        let flattened = text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "\n", with: " ⏎ ")
        return flattened.count > 160 ? String(flattened.prefix(160)) + "…" : flattened
    }

    var symbolName: String {
        switch kind {
        case .text: "doc.on.clipboard"
        case .fileURLs: "doc"
        }
    }
}

/// Testable slice of NSPasteboard.
protocol PasteboardReading {
    var changeCount: Int { get }
    var typeIdentifiers: [String] { get }
    func readString() -> String?
    func readFileURLs() -> [URL]
    /// Writes a string; returns the pasteboard's new change count, or -1 if
    /// the write did not take (so callers never mis-attribute someone else's
    /// change count to themselves).
    @discardableResult
    func write(_ string: String) -> Int
    /// Writes real file URLs back; returns the new change count or -1.
    @discardableResult
    func writeFileURLs(_ paths: [String]) -> Int
}

struct SystemPasteboard: PasteboardReading {
    private var pasteboard: NSPasteboard { .general }

    var changeCount: Int { pasteboard.changeCount }

    var typeIdentifiers: [String] {
        pasteboard.types?.map(\.rawValue) ?? []
    }

    func readString() -> String? {
        pasteboard.string(forType: .string)
    }

    func readFileURLs() -> [URL] {
        (pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? []
    }

    @discardableResult
    func write(_ string: String) -> Int {
        pasteboard.clearContents()
        guard pasteboard.setString(string, forType: .string) else { return -1 }
        return pasteboard.changeCount
    }

    @discardableResult
    func writeFileURLs(_ paths: [String]) -> Int {
        let urls = paths.map { URL(fileURLWithPath: $0) as NSURL }
        pasteboard.clearContents()
        guard !urls.isEmpty, pasteboard.writeObjects(urls) else { return -1 }
        return pasteboard.changeCount
    }
}

/// Local clipboard history for the island's Clip tab. Polls the pasteboard
/// change count (the standard public approach — macOS has no pasteboard
/// notifications) and respects the password-manager conventions: anything
/// marked concealed or transient is never captured.
@MainActor
final class ClipboardHistoryCenter: ObservableObject {
    @Published private(set) var items: [ClipboardHistoryItem] = []
    @Published private(set) var isPaused = false

    /// org.nspasteboard.org conventions honored by password managers.
    static let excludedTypeIdentifiers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
    ]

    private let maxItems = 24
    private let pasteboard: PasteboardReading
    private var nowProvider: () -> Date
    private var lastSeenChangeCount: Int
    /// Change count produced by our own re-copy; skipped so re-copying an old
    /// item doesn't re-capture it at the top.
    private var selfWriteChangeCount: Int?
    /// What our own re-copy wrote, so suppression can verify the pasteboard
    /// still holds it (an external copy can race in and claim the count).
    private var lastSelfWrittenText: String?
    private var pollTimer: Timer?

    init(pasteboard: PasteboardReading = SystemPasteboard(), nowProvider: @escaping () -> Date = Date.init) {
        self.pasteboard = pasteboard
        self.nowProvider = nowProvider
        // Deliberately don't capture whatever was on the pasteboard before
        // MacForge launched.
        lastSeenChangeCount = pasteboard.changeCount
    }

    func start() {
        stop()
        lastSeenChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.8, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.captureIfChanged()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        pollTimer = timer
    }

    func stop() {
        pollTimer?.invalidate()
        pollTimer = nil
    }

    func setPaused(_ paused: Bool) {
        isPaused = paused
        if !paused {
            // Don't retroactively capture what changed while paused.
            lastSeenChangeCount = pasteboard.changeCount
        }
    }

    func clear() {
        items.removeAll()
    }

    func remove(_ item: ClipboardHistoryItem) {
        items.removeAll { $0.id == item.id }
    }

    /// Puts an item back on the system pasteboard. File entries restore the
    /// actual file URLs (falling back to text if none still exist) so pasting
    /// in Finder/Mail yields files again, not a list of names.
    func copyToPasteboard(_ item: ClipboardHistoryItem) {
        let newCount: Int
        switch item.kind {
        case .fileURLs(let paths):
            let existing = paths.filter { FileManager.default.fileExists(atPath: $0) }
            if existing.isEmpty {
                newCount = pasteboard.write(item.text)
            } else {
                newCount = pasteboard.writeFileURLs(existing)
            }
        case .text:
            newCount = pasteboard.write(item.text)
        }
        if newCount >= 0 {
            selfWriteChangeCount = newCount
            lastSelfWrittenText = item.text
        }
        // Move it to the top with a fresh timestamp so history reflects
        // most-recently-used and the relative time reads "now".
        var refreshed = item
        refreshed.capturedAt = nowProvider()
        items.removeAll { $0.id == item.id }
        items.insert(refreshed, at: 0)
    }

    /// One poll tick; exposed for tests.
    func captureIfChanged() {
        let count = pasteboard.changeCount
        guard count != lastSeenChangeCount else { return }
        lastSeenChangeCount = count

        guard !isPaused else { return }
        if let selfWrite = selfWriteChangeCount, count == selfWrite {
            selfWriteChangeCount = nil
            // Only suppress if the pasteboard still holds what we wrote; if an
            // external copy raced in and claimed this change count, fall
            // through and capture it normally.
            if let text = lastSelfWrittenText,
               pasteboard.readString() == text || pasteboard.readFileURLs().map(\.lastPathComponent).joined(separator: ", ") == text {
                lastSelfWrittenText = nil
                return
            }
            lastSelfWrittenText = nil
        }

        let types = Set(pasteboard.typeIdentifiers)
        guard types.isDisjoint(with: Self.excludedTypeIdentifiers) else { return }

        let now = nowProvider()
        let fileURLs = pasteboard.readFileURLs()
        let string = fileURLs.isEmpty ? pasteboard.readString() : nil

        // The type check and content reads are separate cross-process trips.
        // If the pasteboard changed underneath us (e.g. a password manager
        // wrote a concealed item mid-read), discard this capture — the next
        // tick will re-evaluate the new content against its own types.
        guard pasteboard.changeCount == count else { return }

        if !fileURLs.isEmpty {
            let names = fileURLs.map(\.lastPathComponent)
            ingest(ClipboardHistoryItem(
                kind: .fileURLs(fileURLs.map(\.path)),
                text: names.joined(separator: ", "),
                capturedAt: now
            ))
            return
        }

        guard let string,
              !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return
        }
        // Cap enormous payloads (huge code files, logs) to keep memory sane.
        let capped = string.count > 20_000 ? String(string.prefix(20_000)) : string
        ingest(ClipboardHistoryItem(kind: .text, text: capped, capturedAt: now))
    }

    private func ingest(_ item: ClipboardHistoryItem) {
        // Re-copying the same content refreshes its position and timestamp.
        if let existingIndex = items.firstIndex(where: { $0.text == item.text && $0.kind == item.kind }) {
            var existing = items.remove(at: existingIndex)
            existing.capturedAt = item.capturedAt
            items.insert(existing, at: 0)
            return
        }
        items.insert(item, at: 0)
        if items.count > maxItems {
            items.removeLast(items.count - maxItems)
        }
    }
}
